"""initial schema

Revision ID: fc9200b125eb
Revises: 
Create Date: 2026-10-03 20:34:10.448161
"""
from alembic import op
import sqlalchemy as sa


revision = 'fc9200b125eb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capital_ledger',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entry_type', sa.String(length=16), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fee_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('group', sa.String(length=32), nullable=False),
    sa.Column('label', sa.String(length=128), nullable=False),
    sa.Column('value', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=8), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('verify_flag', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('insights',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.Date(), nullable=False),
    sa.Column('period_end', sa.Date(), nullable=False),
    sa.Column('content_md', sa.Text(), nullable=False),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.Column('ready_to_clone', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('niches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('postage_rates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('carrier', sa.String(length=32), nullable=False),
    sa.Column('service', sa.String(length=64), nullable=False),
    sa.Column('weight_class', sa.String(length=32), nullable=False),
    sa.Column('max_weight_g', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('tracked', sa.Boolean(), nullable=False),
    sa.Column('default_for_class', sa.Boolean(), nullable=False),
    sa.Column('last_verified', sa.Date(), nullable=True),
    sa.Column('verify_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.JSON(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('status_message', sa.Text(), nullable=False),
    sa.Column('poll_interval_min', sa.Integer(), nullable=False),
    sa.Column('max_page_loads_per_hour', sa.Integer(), nullable=False),
    sa.Column('min_delay_s', sa.Integer(), nullable=False),
    sa.Column('max_delay_s', sa.Integer(), nullable=False),
    sa.Column('quiet_hours', sa.String(length=16), nullable=False),
    sa.Column('buyer_fee_pct', sa.Float(), nullable=False),
    sa.Column('buyer_fee_fixed', sa.Float(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=False),
    sa.Column('page_loads_window_start', sa.DateTime(), nullable=True),
    sa.Column('page_loads_in_window', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('tasks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('urgent', sa.Boolean(), nullable=False),
    sa.Column('ref_type', sa.String(length=32), nullable=False),
    sa.Column('ref_id', sa.Integer(), nullable=True),
    sa.Column('done', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('done_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('raw_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('listing_type', sa.String(length=16), nullable=False),
    sa.Column('ends_at', sa.DateTime(), nullable=True),
    sa.Column('postage_cost', sa.Float(), nullable=True),
    sa.Column('collection_only', sa.Boolean(), nullable=False),
    sa.Column('location_text', sa.String(length=128), nullable=False),
    sa.Column('postcode_district', sa.String(length=8), nullable=False),
    sa.Column('seller_name', sa.String(length=128), nullable=False),
    sa.Column('seller_feedback', sa.Integer(), nullable=True),
    sa.Column('image_urls', sa.JSON(), nullable=False),
    sa.Column('image_hash', sa.String(length=32), nullable=False),
    sa.Column('condition_text', sa.String(length=64), nullable=False),
    sa.Column('raw', sa.JSON(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['raw_listings.id'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'external_id', name='uq_source_external')
    )
    op.create_table('search_queries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('query', sa.String(length=200), nullable=False),
    sa.Column('filters', sa.JSON(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sold_comps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('completeness', sa.String(length=16), nullable=False),
    sa.Column('sold_price', sa.Float(), nullable=False),
    sa.Column('postage', sa.Float(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sold_comps', schema=None) as batch_op:
        batch_op.create_index('ix_sold_comps_lookup', ['niche_id', 'platform', 'region', 'completeness'], unique=False)

    op.create_table('valuations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('median_price', sa.Float(), nullable=False),
    sa.Column('p25', sa.Float(), nullable=False),
    sa.Column('p75', sa.Float(), nullable=False),
    sa.Column('sold_count', sa.Integer(), nullable=False),
    sa.Column('active_count', sa.Integer(), nullable=False),
    sa.Column('sell_through_rate', sa.Float(), nullable=False),
    sa.Column('est_days_to_sell', sa.Integer(), nullable=False),
    sa.Column('confidence', sa.String(length=8), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('providers', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_valuations_item_key'), ['item_key'], unique=False)

    op.create_table('normalised_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_listing_id', sa.Integer(), nullable=False),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('completeness', sa.String(length=16), nullable=False),
    sa.Column('condition_notes', sa.Text(), nullable=False),
    sa.Column('is_bundle', sa.Boolean(), nullable=False),
    sa.Column('bundle_items', sa.JSON(), nullable=False),
    sa.Column('console_model', sa.String(length=64), nullable=False),
    sa.Column('accessories', sa.JSON(), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('risk_flags', sa.JSON(), nullable=False),
    sa.Column('item_key', sa.String(length=64), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['raw_listing_id'], ['raw_listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('normalised_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_normalised_items_item_key'), ['item_key'], unique=False)

    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_listing_id', sa.Integer(), nullable=False),
    sa.Column('normalised_item_id', sa.Integer(), nullable=False),
    sa.Column('valuation_id', sa.Integer(), nullable=True),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('buy_price', sa.Float(), nullable=False),
    sa.Column('buyer_fees', sa.Float(), nullable=False),
    sa.Column('inbound_cost', sa.Float(), nullable=False),
    sa.Column('landed_cost', sa.Float(), nullable=False),
    sa.Column('expected_sale_price', sa.Float(), nullable=False),
    sa.Column('sell_fees', sa.Float(), nullable=False),
    sa.Column('outbound_postage', sa.Float(), nullable=False),
    sa.Column('packaging', sa.Float(), nullable=False),
    sa.Column('reserve', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('net_margin', sa.Float(), nullable=False),
    sa.Column('roi', sa.Float(), nullable=False),
    sa.Column('est_days_to_sell', sa.Integer(), nullable=False),
    sa.Column('tier', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('distance_miles', sa.Float(), nullable=True),
    sa.Column('collection_only', sa.Boolean(), nullable=False),
    sa.Column('check_manually', sa.Boolean(), nullable=False),
    sa.Column('capital_warning', sa.Boolean(), nullable=False),
    sa.Column('should_alert', sa.Boolean(), nullable=False),
    sa.Column('skip_reason', sa.String(length=200), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('breakdown', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['normalised_item_id'], ['normalised_items.id'], ),
    sa.ForeignKeyConstraint(['raw_listing_id'], ['raw_listings.id'], ),
    sa.ForeignKeyConstraint(['valuation_id'], ['valuations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('raw_listing_id')
    )
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('channel', sa.String(length=16), nullable=False),
    sa.Column('priority', sa.String(length=8), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('inventory_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=32), nullable=False),
    sa.Column('deal_id', sa.Integer(), nullable=True),
    sa.Column('normalised_item_id', sa.Integer(), nullable=True),
    sa.Column('niche_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('platform', sa.String(length=64), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('completeness', sa.String(length=16), nullable=False),
    sa.Column('region', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('cost_basis', sa.Float(), nullable=False),
    sa.Column('purchase_price', sa.Float(), nullable=False),
    sa.Column('purchase_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('expected_sale_price', sa.Float(), nullable=False),
    sa.Column('expected_days_to_sell', sa.Integer(), nullable=False),
    sa.Column('expected_net_profit', sa.Float(), nullable=False),
    sa.Column('weight_class', sa.String(length=32), nullable=False),
    sa.Column('listed_at', sa.DateTime(), nullable=True),
    sa.Column('sold_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['deal_id'], ['deals.id'], ),
    sa.ForeignKeyConstraint(['niche_id'], ['niches.id'], ),
    sa.ForeignKeyConstraint(['normalised_item_id'], ['normalised_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sku')
    )
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('condition_description', sa.Text(), nullable=False),
    sa.Column('item_specifics', sa.JSON(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('markdown_schedule', sa.JSON(), nullable=False),
    sa.Column('photo_shot_list', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_order_id', sa.String(length=128), nullable=False),
    sa.Column('sale_price', sa.Float(), nullable=False),
    sa.Column('postage_charged', sa.Float(), nullable=False),
    sa.Column('platform_fees', sa.Float(), nullable=False),
    sa.Column('payment_fees', sa.Float(), nullable=False),
    sa.Column('postage_cost', sa.Float(), nullable=False),
    sa.Column('packaging_cost', sa.Float(), nullable=False),
    sa.Column('other_costs', sa.Float(), nullable=False),
    sa.Column('net_profit', sa.Float(), nullable=False),
    sa.Column('net_margin', sa.Float(), nullable=False),
    sa.Column('days_to_sell', sa.Integer(), nullable=False),
    sa.Column('sold_at', sa.DateTime(), nullable=False),
    sa.Column('shipped_at', sa.DateTime(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('inventory_item_id', sa.Integer(), nullable=False),
    sa.Column('checklist', sa.JSON(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('grade', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('tested_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['inventory_item_id'], ['inventory_items.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('platform_listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.String(length=32), nullable=False),
    sa.Column('external_id', sa.String(length=128), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('listed_at', sa.DateTime(), nullable=False),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('platform_listings')
    op.drop_table('test_results')
    op.drop_table('sales')
    op.drop_table('listings')
    op.drop_table('inventory_items')
    op.drop_table('alerts')
    op.drop_table('deals')
    with op.batch_alter_table('normalised_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_normalised_items_item_key'))

    op.drop_table('normalised_items')
    with op.batch_alter_table('valuations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_valuations_item_key'))

    op.drop_table('valuations')
    with op.batch_alter_table('sold_comps', schema=None) as batch_op:
        batch_op.drop_index('ix_sold_comps_lookup')

    op.drop_table('sold_comps')
    op.drop_table('search_queries')
    op.drop_table('raw_listings')
    op.drop_table('tasks')
    op.drop_table('sources')
    op.drop_table('settings')
    op.drop_table('postage_rates')
    op.drop_table('niches')
    op.drop_table('insights')
    op.drop_table('fee_config')
    op.drop_table('capital_ledger')
    # ### end Alembic commands ###
